# Generated by Django 4.2.6 on 2023-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('items_required', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/dish')),
            ],
        ),
    ]
