# Generated by Django 4.2.6 on 2023-11-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name_plural': 'dishes'},
        ),
    ]
