# Generated by Django 4.2.6 on 2023-11-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_dishes_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
